apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerceinventoryapi-deployment
  labels:
    app: ecommerceinventoryapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ecommerceinventoryapi
  template:
    metadata:
      labels:
        app: ecommerceinventoryapi
    spec:
      containers:
      - name: ecommerceinventoryapi
        image: amit728/ecommerceinventoryapi:1.0.0
        ports:
        - containerPort: 5003
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: ASPNETCORE_ENVIRONMENT
        - name: ASPNETCORE_URLS
          value: "http://*:5003"
        - name: CONNECTIONSTRINGS__INVENTORYDBCONNECTION
          value: "Server=mssql;Database=InventoryDb;User=sa;Password=@Password12;TrustServerCertificate=True;"
        - name: EUREKA__CLIENT__SERVICEURL
          valueFrom:
            configMapKeyRef:
              name: eureka-config
              key: EUREKA__CLIENT__SERVICEURL
        - name: EUREKA__CLIENT__SHOULDFETCHREGISTRY
          value: "true"
        - name: EUREKA__CLIENT__SHOULDREGISTERWITHEUREKA
          value: "true"
        - name: EUREKA__INSTANCE__IPADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: EUREKA__INSTANCE__PREFERIPADDRESS
          value: "true"
        - name: EUREKA__INSTANCE__APPNAME
          value: "inventory-api"
        - name: EUREKA__INSTANCE__PORT
          value: "5003"
        - name: RABBITMQ__HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: RABBITMQ__HOSTNAME
        - name: RABBITMQ__PORT
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: RABBITMQ__PORT
        - name: RABBITMQ__USERNAME
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: RABBITMQ__USERNAME
        - name: RABBITMQ__PASSWORD
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: RABBITMQ__PASSWORD
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerceinventoryapi-service
spec:
  selector:
    app: ecommerceinventoryapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5003
  type: ClusterIP