apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommercecartapi-deployment
  labels:
    app: ecommercecartapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ecommercecartapi
  template:
    metadata:
      labels:
        app: ecommercecartapi
    spec:
      containers:
      - name: ecommercecartapi
        image: amit728/ecommercecartapi:1.0.0
        ports:
        - containerPort: 5004
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: ASPNETCORE_ENVIRONMENT
        - name: ASPNETCORE_URLS
          value: "http://*:5004"
        - name: CONNECTIONSTRINGS__CARTDBCONNECTION
          value: "Server=mssql;Database=CartDb;User=sa;Password=@Password12;TrustServerCertificate=True;"
        - name: SERVICEURLS__INVENTORYENDPOINT
          value: "http://inventory-api"
        - name: EUREKA__CLIENT__SERVICEURL
          valueFrom:
            configMapKeyRef:
              name: eureka-config
              key: EUREKA__CLIENT__SERVICEURL
        - name: EUREKA__CLIENT__SHOULDFETCHREGISTRY
          value: "true"
        - name: EUREKA__CLIENT__SHOULDREGISTERWITHEUREKA
          value: "true"
        - name: EUREKA__INSTANCE__IPADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: EUREKA__INSTANCE__PREFERIPADDRESS
          value: "true"
        - name: EUREKA__INSTANCE__APPNAME
          value: "cart-api"
        - name: EUREKA__INSTANCE__PORT
          value: "5004"
        - name: RABBITMQ__HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: RABBITMQ__HOSTNAME
        - name: RABBITMQ__PORT
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: RABBITMQ__PORT
        - name: RABBITMQ__USERNAME
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: RABBITMQ__USERNAME
        - name: RABBITMQ__PASSWORD
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: RABBITMQ__PASSWORD
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: ecommercecartapi-service
spec:
  selector:
    app: ecommercecartapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5004
  type: ClusterIP