apiVersion: v1
kind: PersistentVolume
metadata:
  name: mssql-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  # Keeps data even if the PVC is deleted
  hostPath:
    path: /mnt/data/mssql # Path on the node where the data is stored
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-pvc
spec:
  accessModes:
    - ReadWriteOnce  # Pod can mount the volume as read-write
  resources:
    requests:
      storage: 10Gi  # Same size as the PV