apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: default
data:
  RABBITMQ__HOSTNAME: "rabbitmq"
  RABBITMQ__PORT: "5672"
  RABBITMQ__USERNAME: "guest"
  RABBITMQ__PASSWORD: "guest"