services:
  ecommerce.product.api:
    image: ${DOCKER_REGISTRY-}ecommerceproductapi
    build:
      context: .
      dockerfile: eCommerce.Product.API/Dockerfile
    depends_on:
      - ecommerce.productdetail.api
      - ecommerce.inventory.api
      - eureka-server
      - rabbitmq
      - mssql-server
    networks:
      - ecommerce-network

  ecommerce.productdetail.api:
    image: ${DOCKER_REGISTRY-}ecommerceproductdetailapi
    build:
      context: .
      dockerfile: eCommerce.ProductDetail.API/Dockerfile
    depends_on:
      - eureka-server
      - mssql-server
    networks:
      - ecommerce-network

  ecommerce.inventory.api:
    image: ${DOCKER_REGISTRY-}ecommerceinventoryapi
    build:
      context: .
      dockerfile: eCommerce.Inventory.API/Dockerfile
    depends_on:
      - eureka-server
      - rabbitmq
      - mssql-server
    networks:
      - ecommerce-network

  ecommerce.cart.api:
    image: ${DOCKER_REGISTRY-}ecommercecartapi
    build:
      context: .
      dockerfile: eCommerce.Cart.API/Dockerfile
    depends_on:
      - ecommerce.inventory.api
      - eureka-server
      - rabbitmq
      - mssql-server
    networks:
      - ecommerce-network

  ecommerce.notification.api:
    image: ${DOCKER_REGISTRY-}ecommercenotificationapi
    build:
      context: .
      dockerfile: eCommerce.Notification.API/Dockerfile
    depends_on:
      - eureka-server
      - rabbitmq
      - mssql-server
    networks:
      - ecommerce-network

  ecommerce.ocelotapigateway:
    image: ${DOCKER_REGISTRY-}ecommerceocelotapigateway
    build:
      context: .
      dockerfile: eCommerce.OcelotApiGateway/Dockerfile
    depends_on:
      - eureka-server
    networks:
      - ecommerce-network

  eureka-server:
    image: steeltoeoss/eureka-server
    networks:
      - ecommerce-network

  rabbitmq:
    image: rabbitmq:3-management
    networks:
      - ecommerce-network

  mssql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql-server
    networks:
      - ecommerce-network
    volumes:
      - ecommerce_vol:/var/opt/mssql

networks:
  ecommerce-network:
    driver: bridge

volumes:
  ecommerce_vol: